#!/usr/bin/env bash
MARC21=https://data.dnb.de/Buchhaendler/buchhaendlerportraets_dnbmarc_20200708mrc.xml
echo ""
echo "starting retrieval of bookseller portrait data sets!"
echo ""
echo "start retrieving MARC 21 XML ..."
wget $MARC21 -O 'marc21/records.xml' -o wget.log
echo "done retrieving MARC 21 XML!"
echo "start converting MARC 21 XML ..."
catmandu convert MARC --type XML to JSON --pretty 1 < marc21/records.xml > marc21/records.json
echo "done converting MARC 21 XML!"
echo ""
echo "start retrieving METS/MODS XML ..."
catmandu convert dnb-booksellers to JSON --pretty 1 > mets-mods/records.json
echo "done retrieving METS/MODS XML!"
echo ""
echo "done retrieving bookseller portrait data!"
echo ""
